name: romanelli
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base=4.0.3
  - r-ggplot2=3.3.5
  - r-dplyr=1.0.7
  - r-tidyr=1.1.3
  - r-ggrepel=0.9.1
  - bioconductor-deseq2=1.30.1
  - r-stringr=1.4.0
